### ISSUE TITLE
[Improvement] Remove sortable identifiers from the users table

### ISSUE THREAD

**Issue by shepilov** [linagora/twake-drive-legacy#441]
**Context**
Right now we have to join queries in PostgreSQL like this if we want to find docs for the user
```SQL
select * from ext.drive_files f
    where string_to_array(creator, '-') <@ string_to_array('11ee-ba16-ada1e820-959c-6f5013877a67', '-');
```
Because we rearrange string identifiers parts to make it sortable in Cassandra

**TODO**
- [ ] Remove all the code with timeuuid modification
- [ ] Use in drive-file and user table the same identifier
- [ ] Make a migration script to transform data and store only uuid
- [ ] Make sure that we don't sort data by uuid during search requests
